### ISSUE TITLE
vif_type=binding_failed

### ISSUE THREAD

**Issue by kidchang** [kidchang/openstack-ansible#8]
error when trying to bring up an instance: "No Valid host found", error message in nova-conductor.log shown below:

ERROR nova.scheduler.utils [req-0bbba0be-37d0-436f-aaed-16aecb57df68 None] [instance: 3928a402-1649-4d46-95ba-ac6048a9cd00] Error from last host: vagrant-ubuntu-trusty-64 (node vagrant-ubuntu-trusty-64): [u'Traceback (most recent call last):\n', u'  File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 2036, in _do_build_and_run_instance\n    filter_properties)\n', u'  File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 2167, in _build_and_run_instance\n    instance_uuid=instance.uuid, reason=six.text_type(e))\n', u'RescheduledException: Build of instance 3928a402-1649-4d46-95ba-ac6048a9cd00 was re-scheduled: Unexpected vif_type=binding_failed\n']

**Comment by kidchang** [comment]
just noticed that ml2_conf.ini on compute node has nothing in it(all commented out). This might cause the binding_failed error.

**Comment by kidchang** [comment]
@jerryz1982 
I pushed a commit that has some changes to neutron and cinder related config files. Re-ran ansible and tried to bring up an instance, still got that vif_type=bind_failed error. I will look into that later.

**Comment by jerryz1982** [comment]
backlog of what we discussed last night, problem solved.
/etc/neutron/plugins/ml2/ml2_conf.ini 需要添加如下配置
[ml2_type_flat]

flat_networks = external

[ovs]
local_ip = 10.1.0.12   此处为网络节点gre tunnel所在网卡对应的IP
enable_tunneling = True
bridge_mappings = external:br-ex

[agent]
tunnel_types = gre

/etc/nova/nova.conf

my_ip = 10.1.0.13    此处为计算节点本机IP 
vncserver_listen = 10.1.0.13 此处计算节点本机IP
vncserver_proxyclient_address = 10.1.0.11  controller也就是novncproxy所在IP
